all:;g++ -o UnitTest UnitTest.cpp -lwiringPi PID/PID.h PID/PID.cpp Sensor/Sensor.h Sensor/MPU6050.h Sensor/MPU6050.cpp

Tuner:;g++ -o PIDtuner PIDtuner.cpp -lwiringPi -ljansson PID/PID.h PID/PID.cpp Sensor/Sensor.h Sensor/MPU6050.h Sensor/MPU6050.cpp ../Network/TCP_Server.c ../Network/UDP_Server.c ../Network/ctl.c ../Network/network.c ../Network/TCP_Server.h ../Network/UDP_Server.h ../Network/ctl.h ../Network/network.h

